export const jobchinRoutes = {
    personalData: $localize`:@@JobChIN.personalDataRoute:udaje`,
    student: $localize`:@@JobChIN.student:student`,
    company: $localize`:@@JobChIN.company:zamestnavatel`,
    notification: $localize`:@@JobChIN.notificationRoute:notifikace`,
    settings: $localize`:@@JobChIN.settingsRoute:nastaveni`,
    myOffres: $localize`:@@JobChIN.myOffersRoute:moje-nabidky`,
    create: $localize`:@@JobChIN.createRoute:vytvorit`,
    update: $localize`:@@JobChIN.updateRoute:upravit`,
    duplicate: $localize`:@@JobChIN.duplicateRoute:duplikovat`,
    overview: $localize`:@@JobChIN.overviewRoute:prehled`,

    aboutCompany: $localize`:@@JobChIN.aboutCompanyRoute:o-firme`,
    studentSearch: $localize`:@@JobChIN.studentSearchRoute:vyhledavani-studentu`,
    companyType: $localize`:@@JobChIN.companyTypeRoute:typ-uctu`,
    users: $localize`:@@JobChIN.usersRoute:uzivatele`,
    generalInfo: $localize`:@@JobChIN.generalInfoRoute:zakladni-informace`,
    detail: $localize`:@@JobChIN.detailRoute:detail`,
    contactPerson: $localize`:@@JobChIN.contactPersonRoute:kontaktni-osoba`,
    presentation: $localize`:@@JobChIN.presentationRoute:prezentace`,
    candidates: $localize`:@@JobChIN.candidatesRoute:uchazeci`,
    candidateRequest: $localize`:@@JobChIN.candidateRequestRoute:pozadavky-na-uchazece`,
    branches: $localize`:@@JobChIN.branchesRoute:pobocky`,

    cv: $localize`:@@JobChIN.profileRoute:cv`,
    basicInfo: $localize`:@@JobChIN.basicInfoRoute:zakladni-informace`,
    workExperiences: $localize`:@@JobChIN.workExperiencesRoute:pracovni-zkusenosti`,
    skills: $localize`:@@JobChIN.skillsRoute:dovednosti`,
    study: $localize`:@@JobChIN.studyRoute:vzdelani`,
    contact: $localize`:@@JobChIN.contactRoute:kontakt`,
    visibility: $localize`:@@JobChIN.visibilityRoute:viditelnost`,

    notFound: $localize`:@@JobChIN.notFoundRoute:nenalezeno`,
    expired: $localize`:@@JobChIN.expired:expirovano`,
}
